# Generated by Django 5.1.6 on 2025-02-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_category_asset_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpesifikasiPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tinta', models.CharField(blank=True, max_length=50, null=True)),
                ('resolusi_cetak', models.CharField(blank=True, max_length=50, null=True)),
                ('kecepatan_cetak', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
