# Generated by Django 5.1.6 on 2025-02-26 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='category',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_date',
            new_name='tanggal_pembelian',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.AddField(
            model_name='asset',
            name='nama',
            field=models.CharField(default='Nama Default', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Spesifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosesor', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('penyimpanan', models.CharField(blank=True, max_length=100, null=True)),
                ('lain_lain', models.TextField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spesifikasi', to='assets.asset')),
            ],
        ),
    ]
