# Generated by Django 5.1.6 on 2025-02-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_spesifikasiprinter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpesifikasiPrinter',
        ),
    ]
