# Generated by Django 5.1.6 on 2025-02-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_delete_spesifikasiprinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='spesifikasi',
            name='jenis_tinta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='kecepatan_cetak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spesifikasi',
            name='resolusi_cetak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
